# Global Configuration for the SUMO MMRL project.
global:
  project_name: "sumo_mmrl"  # Name of the project
  entity: "ahoope5"         # User or team name

# Training configuration settings.
training_settings:
  episodes: 20000               
  # experiment_path: "Experiments/3x3/"
  # sumoconfig: "Nets/3x3.sumocfg"    
  experiment_path: "Experiments/balt3/"     
  sumoconfig: "Nets/osm.sumocfg"       
  savepath: "models/"                                   
  initial_life: .15                     
  penalty: -0.2                        
            
person_settings:
  start: "-521985670#5"
  destination: "192469470#0"
  # start: "1w"
  # destination: "10e"

# Environment settings.
env:
  num_of_vehicles: 1                     
  num_of_people: 1                       
  types_of_passengers: 1                

# Optuna optimization settings.
optuna:
  n_trials: 20
  storage_path: "sqlite:///db.sqlite3"
  study_name: null                      

agent_hyperparameters:
  learning_rate: 0.00001
  gamma: 0.9999                
  epsilon_decay: 0.9995
  batch_size: 512
  memory_size: 50000
  epsilon_max:  1.0
  epsilon_min: 0.05
  initial_life: .15                     
  penalty: -0.2  



# Logging configuration for Weights & Biases.
wandb:
  metric_name: "cumulative_reward"       # Primary metric for tracking
